-- Run this in Supabase SQL Editor or a local PostgreSQL database.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  address text,
  avatar_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists avatar_url text;

alter table public.profiles enable row level security;
drop policy if exists "Users can view their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "Users can upload their own avatar" on storage.objects;
drop policy if exists "Users can update their own avatar" on storage.objects;
drop policy if exists "Anyone can view avatars" on storage.objects;
create policy "Users can upload their own avatar" on storage.objects for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Users can update their own avatar" on storage.objects for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Anyone can view avatars" on storage.objects for select using (bucket_id = 'avatars');

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  total numeric(10, 2) not null check (total >= 0),
  shipping_address jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0)
);

-- Store catalog used by the admin back office.
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete restrict,
  name text not null,
  slug text not null unique,
  description text,
  short_description text,
  sku text not null unique,
  barcode text,
  price numeric(10, 2) not null check (price >= 0),
  compare_at_price numeric(10, 2) check (compare_at_price is null or compare_at_price >= 0),
  cost_price numeric(10, 2) check (cost_price is null or cost_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  reserved_stock integer not null default 0 check (reserved_stock >= 0),
  low_stock_threshold integer not null default 10 check (low_stock_threshold >= 0),
  weight_grams integer,
  image_url text,
  status text not null default 'active' check (status in ('active', 'draft', 'archived')),
  featured boolean not null default false,
  best_seller boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.categories (name, slug) values
  ('Fruits secs', 'fruits-secs'),
  ('Fruits séchés', 'fruits-seches'),
  ('Mixes', 'mixes'),
  ('Drinks', 'drinks'),
  ('Gift Boxes', 'gift-boxes'),
  ('Custom Mixes', 'custom-mixes')
on conflict (slug) do nothing;

insert into public.products (category_id, name, slug, description, sku, price, stock, low_stock_threshold, weight_grams, image_url, status, featured, best_seller)
select c.id, seed.name, seed.slug, seed.description, seed.sku, seed.price, seed.stock, seed.threshold, seed.weight_grams, seed.image_url, 'active', seed.featured, seed.best_seller
from (values
  ('Energy Mix', 'energy-mix-50g', 'Amande, cajou, noix et fruits séchés.', 'NVT-ENE-050', 12.90::numeric, 50, 10, 50, '/Grab&Go-50g.png', false, true),
  ('Energy Mix', 'energy-mix-100g', 'Le mix qui accompagne vos journées.', 'NVT-ENE-100', 21.90::numeric, 35, 10, 100, '/Standard-100g.png', true, false),
  ('Family Premium', 'family-premium-200g', 'Un généreux mélange à partager.', 'NVT-FAM-200', 36.90::numeric, 24, 8, 200, '/Family-Premium-200g.png', true, true)
) as seed(name, slug, description, sku, price, stock, threshold, weight_grams, image_url, featured, best_seller)
cross join public.categories c
where c.slug = 'mixes'
on conflict (slug) do nothing;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

-- Existing storefront orders use lowercase statuses; admin actions use the
-- normalized uppercase workflow while preserving the same column.
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED'));

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
drop policy if exists "Users can view their own orders" on public.orders;
drop policy if exists "Users can view their own order items" on public.order_items;
create policy "Users can view their own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users can view their own order items" on public.order_items for select using (exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));

notify pgrst, 'reload schema';

-- Admin back office domain. Keep operational entities relational so status, stock,
-- permissions and audit history can be queried independently as the store grows.
create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  name text not null unique check (name in ('SUPER ADMIN', 'ADMIN', 'STAFF')),
  permissions jsonb not null default '{}'::jsonb
);

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id text not null,
  quantity integer not null,
  reason text not null,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  title text not null,
  body text not null,
  entity_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.admin_roles (name, permissions) values
  ('SUPER ADMIN', '{"all": true}'),
  ('ADMIN', '{"orders": true, "products": true, "customers": true, "analytics": true}'),
  ('STAFF', '{"orders": true, "inventory": true}')
on conflict (name) do nothing;

alter table public.admin_users enable row level security;
alter table public.order_status_history enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.admin_notifications enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "Users can view their own order status history" on public.order_status_history;
create policy "Users can view their own order status history" on public.order_status_history
for select using (exists (select 1 from public.orders where orders.id = order_status_history.order_id and orders.user_id = auth.uid()));
