import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/supabase/admin";

type Role = "ADMIN" | "STAFF";
function result(error: unknown) { const message = error instanceof Error ? error.message : "Unable to manage the team."; const status = message === "UNAUTHORIZED" ? 401 : message === "FORBIDDEN" ? 403 : 500; return NextResponse.json({ error: status === 401 ? "Unauthorized" : status === 403 ? "Only a SUPER ADMIN can manage the team." : "Unable to manage the team." }, { status }); }
async function requireSuperAdmin() { const result = await requireAdmin(); if (result.context.role !== "SUPER ADMIN") throw new Error("FORBIDDEN"); return result; }
export async function GET() { try { const { client } = await requireSuperAdmin(); const { data, error } = await client.from("admin_users").select("id,created_at,role:admin_roles(name)").order("created_at", { ascending: false }); if (error) throw error; const ids = (data ?? []).map((item) => item.id); const users = await Promise.all(ids.map(async (id) => { const { data: authUser, error: authError } = await client.auth.admin.getUserById(id); if (authError) throw authError; const relation = Array.isArray(data?.find((item) => item.id === id)?.role) ? data?.find((item) => item.id === id)?.role[0] : data?.find((item) => item.id === id)?.role; return { id, email: authUser.user.email ?? "", created_at: data?.find((item) => item.id === id)?.created_at, role: (relation as { name?: string } | undefined)?.name ?? "STAFF" }; })); return NextResponse.json({ users }); } catch (error) { return result(error); } }
export async function POST(request: Request) { try { const { client } = await requireSuperAdmin(); const body = await request.json() as { email?: string; password?: string; role?: Role }; if (!body.email || !/^\S+@\S+\.\S+$/.test(body.email) || !body.password || body.password.length < 8 || (body.role !== "ADMIN" && body.role !== "STAFF")) return NextResponse.json({ error: "Email, password of 8+ characters, and a valid role are required." }, { status: 400 }); const { data: authData, error: authError } = await client.auth.admin.createUser({ email: body.email.toLowerCase().trim(), password: body.password, email_confirm: true }); if (authError || !authData.user) throw authError ?? new Error("Unable to create user."); const { data: role, error: roleError } = await client.from("admin_roles").select("id").eq("name", body.role).single(); if (roleError) throw roleError; const { error } = await client.from("admin_users").insert({ id: authData.user.id, role_id: role.id }); if (error) throw error; return NextResponse.json({ ok: true, id: authData.user.id }, { status: 201 }); } catch (error) { return result(error); } }
export async function PATCH(request: Request) { try { const { client, context } = await requireSuperAdmin(); const body = await request.json() as { id?: string; role?: Role }; if (!body.id || (body.role !== "ADMIN" && body.role !== "STAFF")) return NextResponse.json({ error: "A user and valid role are required." }, { status: 400 }); if (body.id === context.userId) return NextResponse.json({ error: "You cannot change your own role." }, { status: 400 }); const { data: role, error: roleError } = await client.from("admin_roles").select("id").eq("name", body.role).single(); if (roleError) throw roleError; const { error } = await client.from("admin_users").update({ role_id: role.id }).eq("id", body.id); if (error) throw error; return NextResponse.json({ ok: true }); } catch (error) { return result(error); } }
export async function DELETE(request: Request) { try { const { client, context } = await requireSuperAdmin(); const id = new URL(request.url).searchParams.get("id"); if (!id || id === context.userId) return NextResponse.json({ error: "You cannot remove your own access." }, { status: 400 }); const { error } = await client.from("admin_users").delete().eq("id", id); if (error) throw error; return NextResponse.json({ ok: true }); } catch (error) { return result(error); } }
