import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/supabase/admin";

const allowedStatuses = ["NEW", "CONFIRMED", "PREPARING", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "RETURNED"] as const;
function responseFor(error: unknown) { const message = error instanceof Error ? error.message : "Unable to process request."; return NextResponse.json({ error: message === "UNAUTHORIZED" ? "Unauthorized" : message === "FORBIDDEN" ? "Admin access required" : "Unable to load orders." }, { status: message === "UNAUTHORIZED" ? 401 : message === "FORBIDDEN" ? 403 : 500 }); }

export async function GET(request: Request) { try { const { client } = await requireAdmin(); const url = new URL(request.url); const query = url.searchParams.get("q")?.trim(); let requestQuery = client.from("orders").select("id,email,status,total,shipping_address,created_at,order_items(product_name,quantity,unit_price)").order("created_at", { ascending: false }); if (query) requestQuery = requestQuery.ilike("email", `%${query}%`); const { data, error } = await requestQuery; if (error) throw error; return NextResponse.json({ orders: data ?? [] }); } catch (error) { return responseFor(error); } }

export async function PATCH(request: Request) { try { const { client, context } = await requireAdmin(); const body = await request.json() as { id?: string; status?: string; note?: string }; if (!body.id || !body.status || !allowedStatuses.includes(body.status as typeof allowedStatuses[number])) return NextResponse.json({ error: "Invalid order status." }, { status: 400 }); const { error } = await client.from("orders").update({ status: body.status }).eq("id", body.id); if (error) throw error; const historyError = await client.from("order_status_history").insert({ order_id: body.id, status: body.status, changed_by: context.userId, note: body.note ?? null }); if (historyError.error) throw historyError.error; await client.from("audit_logs").insert({ admin_id: context.userId, action: "changed_status", entity_type: "order", entity_id: body.id, details: { status: body.status } }); return NextResponse.json({ ok: true }); } catch (error) { return responseFor(error); } }
