"use client";

import Link from "next/link";
import { Download, MoreHorizontal, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { formatTnd, statusLabel, type AdminOrder, type OrderStatus } from "@/lib/admin-data";

const statuses: OrderStatus[] = ["NEW", "CONFIRMED", "PREPARING", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "RETURNED"];
type ApiOrder = { id: string; email: string; status: string; total: number; created_at: string; shipping_address: { firstName?: string; lastName?: string; phone?: string } | null; order_items?: { product_name: string; quantity: number }[] };
function mapOrder(order: ApiOrder): AdminOrder { const address = order.shipping_address ?? {}; const status = statuses.includes(order.status as OrderStatus) ? order.status as OrderStatus : "NEW"; return { id: order.id, customer: `${address.firstName ?? "Customer"} ${address.lastName ?? ""}`.trim(), phone: address.phone ?? "", date: new Date(order.created_at).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }), products: `${order.order_items?.[0]?.product_name ?? "Order items"} + ${Math.max(0, (order.order_items?.length ?? 1) - 1)}`, total: Number(order.total), payment: "COD · Pending", status }; }
export function LiveOrdersView() { const [orders, setOrders] = useState<AdminOrder[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { fetch("/api/admin/orders").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setOrders((body.orders as ApiOrder[]).map(mapOrder)); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Unable to load orders.")).finally(() => setLoading(false)); }, []); const filtered = useMemo(() => orders.filter((order) => `${order.id} ${order.customer} ${order.phone}`.toLowerCase().includes(query.toLowerCase())), [orders, query]); async function updateStatus(id: string, status: OrderStatus) { const match = orders.find((order) => order.id === id); if (!match) return; const response = await fetch("/api/admin/orders", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: id, status }) }); if (!response.ok) { setError("Order status could not be updated."); return; } setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); }
return <><div className="admin-page-heading"><div><p className="admin-eyebrow">Sales & fulfilment</p><h1>Orders</h1><p>{loading ? "Loading orders..." : `${orders.length} orders across all channels.`}</p></div><button className="admin-dark-button"><Download size={15} /> Export CSV</button></div><section className="admin-panel"><div className="panel-heading"><h2>All orders</h2><label className="table-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search orders..." /></label></div>{error && <p className="admin-form-error">{error}</p>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((order) => <tr key={order.id}><td><Link className="order-id" href={`/admin/orders/${order.id}`}>#{order.id.slice(0, 8).toUpperCase()}</Link></td><td><strong>{order.customer}</strong><small>{order.phone}</small></td><td>{order.date}</td><td><strong>{formatTnd(order.total)}</strong><small>{order.payment}</small></td><td><select className="status-select" value={order.status} onChange={(event) => updateStatus(order.id, event.target.value as OrderStatus)}>{statuses.map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select></td><td><button className="table-more" title="More actions"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table>{!loading && !filtered.length && <div className="admin-empty"><strong>No orders found</strong><span>New customer orders will appear here.</span></div>}</div></section></>; }
