"use client";

import { ArrowDownRight, ArrowUpRight, Boxes, ChevronDown, CircleAlert, Download, MoreHorizontal, PackageCheck, Plus, Search, ShoppingBag, TrendingUp, Users } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { adminOrders, formatTnd, inventoryItems, statusLabel, type AdminOrder, type OrderStatus } from "@/lib/admin-data";
import { products } from "@/lib/catalog";

const statusOptions: OrderStatus[] = ["NEW", "CONFIRMED", "PREPARING", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED", "RETURNED"];
const chartValues = [38, 52, 44, 68, 56, 73, 61, 84, 67, 78, 92, 76, 88, 81, 96, 72, 87, 99, 83, 91, 76, 88, 100, 94];

function PageHeading({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) { return <div className="admin-page-heading"><div><p className="admin-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{action}</div>; }
function StatusBadge({ status }: { status: OrderStatus }) { return <span className={`status-badge status-${status.toLowerCase()}`}><i />{statusLabel(status)}</span>; }
function Kpi({ label, value, delta, icon: Icon, tone = "gold" }: { label: string; value: string; delta?: string; icon: typeof TrendingUp; tone?: string }) { return <div className="kpi-card"><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><span>{label}</span><strong>{value}</strong>{delta && <small className={delta.startsWith("-") ? "negative" : "positive"}>{delta.startsWith("-") ? <ArrowDownRight size={13} /> : <ArrowUpRight size={13} />}{delta}</small>}</div>; }
function Panel({ title, action, children, className = "" }: { title: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`admin-panel ${className}`}><div className="panel-heading"><h2>{title}</h2>{action}</div>{children}</section>; }

export function DashboardView() { const [range, setRange] = useState("Last 30 days"); return <><PageHeading eyebrow="Monday, 7 September 2026" title="Good morning, NUTVORA." copy="Here’s what’s happening with your store today." action={<button className="admin-outline-button"><Download size={15} /> Export report</button>} /><div className="kpi-grid"><Kpi label="Today's sales" value="1,248.90 TND" delta="18.4%" icon={TrendingUp} /><Kpi label="Today's orders" value="24" delta="12.2%" icon={ShoppingBag} tone="ink" /><Kpi label="Pending orders" value="23" icon={PackageCheck} tone="peach" /><Kpi label="Low stock" value="08" delta="-4 items" icon={CircleAlert} tone="rose" /></div><div className="admin-dashboard-grid"><Panel title="Sales overview" action={<select value={range} onChange={(event) => setRange(event.target.value)}><option>Today</option><option>Last 7 days</option><option>Last 30 days</option><option>This month</option></select>} className="sales-panel"><div className="chart-summary"><strong>12,850.00 TND</strong><span><ArrowUpRight size={14} /> 18.4% vs previous period</span></div><div className="sales-chart" aria-label="Sales chart">{chartValues.map((value, index) => <span style={{ height: `${value}%` }} key={index} />)}</div><div className="chart-labels"><span>01 Sep</span><span>08 Sep</span><span>15 Sep</span><span>22 Sep</span><span>30 Sep</span></div></Panel><Panel title="Order status" action={<button className="panel-link">View all</button>}><div className="order-donut"><div><strong>184</strong><span>orders</span></div></div><div className="legend"><span><i className="dot new" /> New <b>23</b></span><span><i className="dot prep" /> Preparing <b>31</b></span><span><i className="dot ready" /> Delivered <b>118</b></span><span><i className="dot muted" /> Other <b>12</b></span></div></Panel></div><div className="admin-dashboard-grid lower"><Panel title="Recent orders" action={<Link className="panel-link" href="/admin/orders">View all orders</Link>}><OrderTable rows={adminOrders.slice(0, 4)} /></Panel><Panel title="Stock attention" action={<Link className="panel-link" href="/admin/inventory">Manage inventory</Link>}><div className="stock-list">{inventoryItems.filter((item) => item.stock <= item.threshold).map((item) => <div className="stock-row" key={item.id}><span className="stock-product"><b>{item.product.slice(0, 1)}</b><span><strong>{item.product}</strong><small>{item.sku}</small></span></span><span className={item.stock === 0 ? "out" : "low"}>{item.stock === 0 ? "Out of stock" : `${item.stock} left`}</span></div>)}</div></Panel></div></>; }

function OrderTable({ rows, onStatus }: { rows: AdminOrder[]; onStatus?: (id: string, status: OrderStatus) => void }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Total</th><th>Status</th><th /></tr></thead><tbody>{rows.map((order) => <tr key={order.id}><td><a className="order-id" href={`/admin/orders/${order.id}`}>#{order.id}</a></td><td><strong>{order.customer}</strong><small>{order.phone}</small></td><td>{order.date}</td><td><strong>{formatTnd(order.total)}</strong><small>{order.payment}</small></td><td>{onStatus ? <select className="status-select" value={order.status} onChange={(event) => onStatus(order.id, event.target.value as OrderStatus)}>{statusOptions.map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select> : <StatusBadge status={order.status} />}</td><td><button className="table-more" title="More actions"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table>{!rows.length && <EmptyState title="No orders found" copy="New customer orders will appear here." />}</div>; }

export function OrdersView() { const [query, setQuery] = useState(""); const [orders, setOrders] = useState(adminOrders); const filtered = useMemo(() => orders.filter((order) => `${order.id} ${order.customer} ${order.phone}`.toLowerCase().includes(query.toLowerCase())), [orders, query]); function updateStatus(id: string, status: OrderStatus) { setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); } return <><PageHeading eyebrow="Sales & fulfilment" title="Orders" copy={`${orders.length} orders across all channels.`} action={<button className="admin-dark-button"><Download size={15} /> Export CSV</button>} /><Panel title="All orders" action={<div className="table-actions"><label className="table-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search orders..." /></label><button className="admin-filter"><SlidersIcon /> Filter</button></div>}><OrderTable rows={filtered} onStatus={updateStatus} /></Panel></>; }
function SlidersIcon() { return <span className="filter-lines"><i /><i /><i /></span>; }

export function InventoryView() { const [items, setItems] = useState(inventoryItems); function adjust(id: string, amount: number) { setItems((current) => current.map((item) => item.id === id ? { ...item, stock: Math.max(0, item.stock + amount) } : item)); } return <><PageHeading eyebrow="Catalog operations" title="Inventory" copy="Keep every NUTVORA product ready to ship." action={<button className="admin-dark-button"><Plus size={15} /> Adjust stock</button>} /><div className="inventory-summary"><div><Boxes size={18} /><span>Inventory value</span><strong>18,492 TND</strong></div><div><CircleAlert size={18} /><span>Needs attention</span><strong>3 products</strong></div><div><PackageCheck size={18} /><span>Units available</span><strong>173 units</strong></div></div><Panel title="Stock levels" action={<button className="admin-filter">All categories <ChevronDown size={14} /></button>}><div className="admin-table-wrap"><table className="admin-table inventory-table"><thead><tr><th>Product</th><th>SKU</th><th>Current stock</th><th>Reserved</th><th>Available</th><th>Threshold</th><th>Status</th><th /></tr></thead><tbody>{items.map((item) => { const available = item.stock - item.reserved; const state = item.stock === 0 ? "out" : item.stock <= item.threshold ? "low" : "good"; return <tr key={item.id}><td><strong>{item.product}</strong><small>{item.category}</small></td><td>{item.sku}</td><td><strong>{item.stock}</strong></td><td>{item.reserved}</td><td>{available}</td><td>{item.threshold}</td><td><span className={`stock-status ${state}`}><i />{state === "good" ? "In stock" : state === "low" ? "Low stock" : "Out of stock"}</span></td><td><div className="stock-controls"><button onClick={() => adjust(item.id, -1)} title="Remove stock">−</button><button onClick={() => adjust(item.id, 1)} title="Add stock">+</button></div></td></tr>; })}</tbody></table></div></Panel></>; }

export function ProductsView() { const [query, setQuery] = useState(""); const filtered = products.filter((product) => `${product.name} ${product.format} ${product.category}`.toLowerCase().includes(query.toLowerCase())); return <><PageHeading eyebrow="Catalog" title="Products" copy={`${products.length} products in your catalog.`} action={<button className="admin-dark-button"><Plus size={15} /> Add product</button>} /><Panel title="Product catalog" action={<div className="table-actions"><label className="table-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products..." /></label><button className="admin-filter">Columns <ChevronDown size={14} /></button></div>}><div className="admin-table-wrap"><table className="admin-table products-table"><thead><tr><th>Product</th><th>Category</th><th>SKU</th><th>Price</th><th>Stock</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><span className="product-cell"><img src={product.image} alt="" /><span><strong>{product.name}</strong><small>{product.format} · {product.detail}</small></span></span></td><td>{product.category}</td><td>NVT-{product.id.toUpperCase()}</td><td><strong>{formatTnd(product.price)}</strong></td><td>42</td><td><span className="stock-status good"><i />Active</span></td><td><button className="table-more"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table>{!filtered.length && <EmptyState title="No products found" copy="Try another search term." />}</div></Panel></>; }

export function CustomersView() { const customers = [{ name: "Ahmed Ben Ali", email: "ahmed.benali@email.tn", orders: 8, spent: 438.2, last: "Today" }, { name: "Sarra Mansour", email: "sarra.mansour@email.tn", orders: 5, spent: 219.5, last: "Today" }, { name: "Yassine Trabelsi", email: "yassine.t@email.tn", orders: 3, spent: 164.7, last: "Yesterday" }, { name: "Meriem Gharbi", email: "meriem.g@email.tn", orders: 2, spent: 77.4, last: "Yesterday" }]; return <><PageHeading eyebrow="Relationships" title="Customers" copy="Know the people behind every order." action={<button className="admin-dark-button"><Download size={15} /> Export CSV</button>} /><div className="kpi-grid customer-kpis"><Kpi label="Total customers" value="126" delta="8.7%" icon={Users} /><Kpi label="New this month" value="18" delta="24.1%" icon={TrendingUp} tone="ink" /><Kpi label="Average order value" value="38.90 TND" icon={CircleAlert} tone="peach" /></div><Panel title="All customers" action={<label className="table-search"><Search size={15} /><input placeholder="Search customers..." /></label>}><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Orders</th><th>Total spent</th><th>Last order</th><th>Status</th><th /></tr></thead><tbody>{customers.map((customer) => <tr key={customer.email}><td><span className="customer-cell"><b>{customer.name.slice(0, 1)}</b><span><strong>{customer.name}</strong><small>{customer.email}</small></span></span></td><td>{customer.orders}</td><td><strong>{formatTnd(customer.spent)}</strong></td><td>{customer.last}</td><td><span className="stock-status good"><i />Active</span></td><td><button className="table-more"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div></Panel></>; }

function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="admin-empty"><div><PackageCheck size={21} /></div><strong>{title}</strong><span>{copy}</span></div>; }
