"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ChevronRight, Sparkles } from "lucide-react";
import { Header, ProductCard } from "@/components/store";
import { products } from "@/lib/catalog";
import { usePreferences } from "@/lib/i18n";

const copy = {
  fr: {
    hero: { eyebrow: "NOIX · FRUITS SECs · BOISSONS NATURELLES", title: "Snack Better.", accent: "Feel Better.", description: "Des fruits secs, fruits séchés et boissons naturelles soigneusement sélectionnés pour accompagner votre quotidien.", discover: "Découvrir nos produits", gifts: "Nos coffrets cadeaux", quality: "Qualité premium", natural: "100% naturel", nutrients: "Riche en nutriments" },
    collections: { eyebrow: "L’univers NUTVORA", title: "Nos Collections", shop: "Voir toute la boutique", discover: "Découvrir", items: [["Fruits Secs", "Noix, amandes, cajou et plus"], ["Fruits Séchés", "Ananas, kiwi, mangue et plus"], ["Nos Mix", "Des mélanges gourmands et équilibrés"], ["Coffrets", "Des attentions qui ont du goût"]] },
    products: { eyebrow: "Les favoris de la communauté", title: "Meilleures ventes", shop: "Explorer la sélection" },
    mix: { eyebrow: "Votre recette, votre énergie", title: "Composez votre", accent: "propre Mix.", description: "Choisissez vos ingrédients préférés et créez une composition qui vous ressemble.", action: "Créer mon Mix" },
    trust: [["Livraison rapide", "Partout en Tunisie"], ["Paiement sécurisé", "À la livraison ou en ligne"], ["Emballage soigné", "Chaque commande compte"], ["Satisfaction garantie", "Un service à votre écoute"]],
    footer: { category: "Boutique", info: "Informations", newsletter: "Le mot du jour", newsletterCopy: "Recevez nos nouveautés et offres exclusives.", email: "Votre adresse email", subscribe: "S'inscrire", about: "À propos", delivery: "Livraison", faq: "FAQ", contact: "Contact", rights: "© 2026 NUTVORA. Tous droits réservés", socials: "Instagram · Facebook · TikTok" }
  },
  en: {
    hero: { eyebrow: "NUTS · DRIED FRUITS · NATURAL DRINKS", title: "Snack Better.", accent: "Feel Better.", description: "Carefully selected nuts, dried fruits and natural drinks for every part of your day.", discover: "Discover our products", gifts: "Our gift boxes", quality: "Premium quality", natural: "100% natural", nutrients: "Rich in nutrients" },
    collections: { eyebrow: "The NUTVORA universe", title: "Our Collections", shop: "View the full shop", discover: "Discover", items: [["Nuts", "Walnuts, almonds, cashews and more"], ["Dried Fruits", "Pineapple, kiwi, mango and more"], ["Our Mixes", "Generous and balanced blends"], ["Gift Boxes", "Thoughtful gifts with taste"]] },
    products: { eyebrow: "Community favorites", title: "Best sellers", shop: "Explore the selection" },
    mix: { eyebrow: "Your recipe, your energy", title: "Create your", accent: "own Mix.", description: "Choose your favorite ingredients and create a blend that feels like you.", action: "Create my Mix" },
    trust: [["Fast delivery", "Across Tunisia"], ["Secure payment", "On delivery or online"], ["Careful packaging", "Every order matters"], ["Satisfaction guaranteed", "A service that listens"]],
    footer: { category: "Shop", info: "Information", newsletter: "Word of the day", newsletterCopy: "Receive our latest news and exclusive offers.", email: "Your email address", subscribe: "Subscribe", about: "About us", delivery: "Delivery", faq: "FAQ", contact: "Contact", rights: "© 2026 NUTVORA. All rights reserved", socials: "Instagram · Facebook · TikTok" }
  },
  ar: {
    hero: { eyebrow: "مكسرات · فواكه مجففة · مشروبات طبيعية", title: "تناول أفضل.", accent: "عِش أفضل.", description: "مكسرات وفواكه مجففة ومشروبات طبيعية مختارة بعناية لكل يوم.", discover: "اكتشف منتجاتنا", gifts: "علب الهدايا", quality: "جودة ممتازة", natural: "طبيعي 100٪", nutrients: "غني بالعناصر الغذائية" },
    collections: { eyebrow: "عالم NUTVORA", title: "مجموعاتنا", shop: "شاهد المتجر", discover: "اكتشف", items: [["مكسرات", "جوز ولوز وكاجو والمزيد"], ["فواكه مجففة", "أناناس وكيوي ومانجو والمزيد"], ["خلطاتنا", "خلطات غنية ومتوازنة"], ["علب الهدايا", "هدايا مميزة بطعم رائع"]] },
    products: { eyebrow: "المفضلة لدى المجتمع", title: "الأكثر مبيعاً", shop: "استكشف الاختيارات" },
    mix: { eyebrow: "وصفتك، طاقتك", title: "اصنع", accent: "خلطتك الخاصة", description: "اختر مكوناتك المفضلة وأنشئ خلطة تشبهك.", action: "أنشئ خلطتي" },
    trust: [["توصيل سريع", "في كامل تونس"], ["دفع آمن", "عند التوصيل أو عبر الإنترنت"], ["تغليف بعناية", "كل طلب يهمنا"], ["رضا مضمون", "خدمة تستمع إليك"]],
    footer: { category: "المتجر", info: "معلومات", newsletter: "كلمة اليوم", newsletterCopy: "احصل على آخر الأخبار والعروض الحصرية.", email: "بريدك الإلكتروني", subscribe: "اشتراك", about: "من نحن", delivery: "التوصيل", faq: "الأسئلة الشائعة", contact: "اتصل بنا", rights: "© 2026 NUTVORA. جميع الحقوق محفوظة", socials: "إنستغرام · فيسبوك · تيك توك" }
  }
} as const;

const productCopy = {
  fr: [["Energy Mix", "Amande, cajou, noix & fruits séchés", "Bestseller"], ["Energy Mix", "Le mix qui accompagne vos journées", "Préféré"], ["Family / Premium", "Un généreux mélange à partager", ""], ["Discovery Box", "Une sélection NUTVORA à offrir", "Coffret"]],
  en: [["Energy Mix", "Almonds, cashews, walnuts & dried fruits", "Bestseller"], ["Energy Mix", "The blend that follows your day", "Favorite"], ["Family / Premium", "A generous blend to share", ""], ["Discovery Box", "A NUTVORA selection to gift", "Gift box"]],
  ar: [["خلطة الطاقة", "لوز وكاجو وجوز وفواكه مجففة", "الأكثر مبيعاً"], ["خلطة الطاقة", "خلطة ترافق يومك", "المفضلة"], ["العائلية · ممتازة", "خلطة غنية للمشاركة", ""], ["علبة الاكتشاف", "اختيارات NUTVORA كهدية", "علبة هدايا"]]
} as const;

export default function LocalizedHome() {
  const { locale } = usePreferences();
  const text = copy[locale];
  const translatedProducts = products.map((product, index) => ({ ...product, name: productCopy[locale][index][0], detail: productCopy[locale][index][1], badge: productCopy[locale][index][2] || undefined }));
  const footerBrand = locale === "ar" ? "مكسرات · فواكه مجففة · مشروبات طبيعية" : locale === "en" ? "Nuts · Dried Fruits · Fresh Drinks" : "Noix · Fruits Séchés · Boissons Naturelles";
  const footerNote = locale === "ar" ? "تناول أفضل. عِش أفضل." : locale === "en" ? "Snack better. Feel better." : "Snack better. Feel better.";
  return <main><Header /><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{text.hero.eyebrow}</p><h1>{text.hero.title}<br /><em>{text.hero.accent}</em></h1><p className="hero-description">{text.hero.description}</p><div className="hero-actions"><Link className="button button-dark" href={`/${locale}/shop`}>{text.hero.discover} <ArrowRight size={16} /></Link><Link className="text-link" href={`/${locale}/shop?category=Coffrets`}>{text.hero.gifts} <ChevronRight size={15} /></Link></div><div className="hero-benefits"><span><Sparkles size={16} /> {text.hero.quality}</span><span>◌ {text.hero.natural}</span><span>↗ {text.hero.nutrients}</span></div></div></section><section className="marquee"><span>{locale === "ar" ? "جودة يمكنك تذوقها" : locale === "en" ? "QUALITY YOU CAN TASTE" : "QUALITÉ QUI SE GOÛTE"}</span><i>✦</i><span>{locale === "ar" ? "طاقة للمشاركة" : locale === "en" ? "ENERGY TO SHARE" : "ÉNERGIE QUI SE PARTAGE"}</span><i>✦</i><span>{locale === "ar" ? "جودة يمكنك تذوقها" : locale === "en" ? "QUALITY YOU CAN TASTE" : "QUALITÉ QUI SE GOÛTE"}</span></section><section className="section collections" id="collections"><div className="section-heading"><div><p className="eyebrow">{text.collections.eyebrow}</p><h2>{text.collections.title}</h2></div><Link className="text-link" href={`/${locale}/shop`}>{text.collections.shop} <ArrowRight size={15} /></Link></div><div className="collection-grid">{text.collections.items.map((item, index) => <Link className="collection-card" href={`/${locale}${["/shop?category=Fruits%20secs", "/shop?category=Fruits%20séchés", "/shop?category=Mix", "/shop?category=Coffrets"][index]}`} key={item[0]}><span className="card-number">{String(index + 1).padStart(2, "0")}</span><Image src={[
    "/Standard-100g.png", "/Grab&Go-50g.png", "/Family-Premium-200g.png", "/logo-brand.png"
  ][index]} alt={item[0]} width={320} height={300} /><div><h3>{item[0]}</h3><p>{item[1]}</p><span className="discover">{text.collections.discover} <ArrowRight size={15} /></span></div></Link>)}</div></section><section className="section products-section" id="products"><div className="section-heading"><div><p className="eyebrow">{text.products.eyebrow}</p><h2>{text.products.title}</h2></div><Link className="text-link" href={`/${locale}/shop`}>{text.products.shop} <ArrowRight size={15} /></Link></div><div className="product-grid">{translatedProducts.map((product) => <ProductCard product={product} key={product.id} />)}</div></section><section className="mix-banner"><div><p className="eyebrow">{text.mix.eyebrow}</p><h2>{text.mix.title}<br /><em>{text.mix.accent}</em></h2><p>{text.mix.description}</p><Link className="button button-gold" href={`/${locale}/shop`}>{text.mix.action} <ArrowRight size={16} /></Link></div><div className="mix-orbit"><Image src="/Grab&Go-50g.png" alt={locale === "ar" ? "خلطة NUTVORA مخصصة" : "Custom NUTVORA mix"} width={400} height={400} /></div></section><section className="trust" id="about">{text.trust.map((item, index) => <div key={item[0]}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item[0]}</strong><p>{item[1]}</p></div>)}</section><footer><div className="footer-top"><div><Link className="wordmark footer-logo" href={`/${locale}`}>NUTVORA<span>®</span></Link><p>{footerBrand}</p><p className="footer-note">{footerNote}</p></div><div><h4>{text.footer.category}</h4><Link href={`/${locale}/shop?category=Fruits%20secs`}>{text.collections.items[0][0]}</Link><Link href={`/${locale}/shop?category=Fruits%20séchés`}>{text.collections.items[1][0]}</Link><Link href={`/${locale}/shop?category=Mix`}>{text.collections.items[2][0]}</Link><Link href={`/${locale}/shop?category=Coffrets`}>{text.collections.items[3][0]}</Link></div><div><h4>{text.footer.info}</h4><Link href={`/${locale}/#about`}>{text.footer.about}</Link><Link href={`/${locale}/checkout`}>{text.footer.delivery}</Link><Link href={`/${locale}/checkout`}>{text.footer.faq}</Link><Link href={`/${locale}/#top`}>{text.footer.contact}</Link></div><div className="newsletter"><h4>{text.footer.newsletter}</h4><p>{text.footer.newsletterCopy}</p><div><input type="email" placeholder={text.footer.email} aria-label={text.footer.email} /><button aria-label={text.footer.subscribe}><ArrowRight size={17} /></button></div></div></div><div className="footer-bottom"><span>{text.footer.rights}</span><span>{text.footer.socials}</span></div></footer></main>;
}
