"use client";

import { Check, ChevronRight, Package, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { formatTnd, statusLabel, type OrderStatus } from "@/lib/admin-data";

type Order = { id: string; status: string; total: number; created_at: string; order_items?: { product_name: string; quantity: number; unit_price: number }[]; order_status_history?: { status: string; note: string | null; created_at: string }[] };
const steps: OrderStatus[] = ["NEW", "CONFIRMED", "PREPARING", "READY", "OUT_FOR_DELIVERY", "DELIVERED"];
function normalize(status: string): OrderStatus { return (status === "pending" ? "NEW" : status === "confirmed" ? "CONFIRMED" : status === "shipped" ? "OUT_FOR_DELIVERY" : status.toUpperCase()) as OrderStatus; }
export function OrderTracking() { const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); useEffect(() => { fetch("/api/account/orders").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setOrders(body.orders); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Impossible de charger vos commandes.")).finally(() => setLoading(false)); }, []); if (loading) return <section className="orders-account"><div className="profile-section-heading"><p className="eyebrow">Suivi en direct</p><h2>Mes commandes</h2></div><p className="profile-loading">Chargement de vos commandes...</p></section>; return <section className="orders-account"><div className="profile-section-heading"><div><p className="eyebrow">Suivi en direct</p><h2>Mes commandes</h2><p>Suivez chaque étape de vos commandes NUTVORA.</p></div></div>{error && <p className="auth-error">{error}</p>}{!error && !orders.length && <div className="account-empty"><Package size={24} /><strong>Vous n&apos;avez pas encore de commande.</strong><span>Vos commandes apparaîtront ici après votre achat.</span></div>}<div className="account-orders">{orders.map((order) => { const current = normalize(order.status); const currentIndex = steps.indexOf(current); return <article className="account-order" key={order.id}><div className="account-order-header"><div><span className="eyebrow">Commande du {new Date(order.created_at).toLocaleDateString("fr-FR")}</span><h3>#{order.id.slice(0, 8).toUpperCase()}</h3></div><strong>{formatTnd(Number(order.total))}</strong></div><div className="account-order-items">{(order.order_items ?? []).map((item) => <span key={`${order.id}-${item.product_name}`}>{item.quantity} × {item.product_name}</span>)}</div><div className="tracking-steps">{steps.map((step, index) => <div className={`tracking-step ${index <= currentIndex ? "complete" : ""} ${step === current ? "current" : ""}`} key={step}><span>{index <= currentIndex ? <Check size={12} /> : index + 1}</span><small>{statusLabel(step)}</small></div>)}</div><div className="order-history">{(order.order_status_history ?? []).slice(-4).map((event) => <div key={`${event.status}-${event.created_at}`}><span>{new Date(event.created_at).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</span><strong>{statusLabel(normalize(event.status))}</strong><small>{event.note ?? "Votre commande a été mise à jour."}</small></div>)}{!order.order_status_history?.length && <div><Truck size={14} /><small>Votre commande est en cours de traitement.</small><ChevronRight size={14} /></div>}</div></article>; })}</div></section>; }
